### ISSUE TITLE
eslint-plugin-prettier runs afoul of TOOLS-1826 check-eslint target

### ISSUE THREAD

**Issue by cburroughs** [joyent/node-triton-package-boilerplate#4]
```
ops! Something went wrong! :(

ESLint: 4.13.1.
ESLint couldn't find the plugin "eslint-plugin-prettier". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-prettier is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-prettier@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.

make: *** [tools/mk/Makefile.targ:201: check-eslint] Error 1
```

Is there a usecase besides the make-check-bot for doing less than a full npm install?

**Comment by cburroughs** [comment]
In review of #5 it was pointed out that that this repo probably shouldn't be using this sdcnode related makefile to begin with, but anything that did would run into the same issue.

**Comment by trentm** [comment]
This started as work for TOOLS-2364 to just update the eng git dep to
get the TOOLS-2351 "fix" to `make check-eslint` that would use
`npm install --only=dev` to get the deps need to run eslint. However,
that fails as well:

```
$ npm install --only=dev
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.

added 331 packages from 288 contributors and audited 797 packages in 6.279s
found 0 vulnerabilities

$ make check-eslint
./node_modules/.bin/eslint lib/package-boilerplate.js lib/shapes.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/trentm/bugs/tools-2364-enggitupdatecheckeslint/node-triton-package-boilerplate/node_modules/readable-stream/lib/_stream_readable.js:67:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
make: *** [check-eslint] Error 1
```

This is because of a long standing bug in `npm install --only=dev`:
https://github.com/npm/npm/issues/12184


Then I attempt to move to the latest eng.git using a git submodule (more
common in many of our top-level component repos). I ran into a few warts
(ENGBLD_REQUIRE, ENGBLD_SKIP_VALIDATE_BUILDENV, bug in 'make clean' if NAME
isn't set) and bugs using eng.git with simple node module repos. I decided to
drop using eng.git Makefiles. They add a lot of noise and few warts without much
utility for simple node modules. Noise examples are all the make targets

```
$ make <TAB>
Makefile            check-jsstyle       package.json
all                 check-version       prepush
check               clean               stamp-%
check-bash          cscope.files        test
check-eslint        cutarelease         test-coverage-unit
check-jsl           distclean           test-unit
check-jsl-node      docs                xref
check-jsl-web       fmt
check-json          git-hooks
```

vs. after my change:

```
$ make
Makefile            check-version       git-hooks
all                 clean               test-coverage-unit
check               cutarelease         test-unit
check-eslint        fmt
```

The resulting Makefile is, I feel much simpler and self-explanatory. The
only loss that I know of is `make check-copyright`. A fair trade.
